title: 'Gryfh'
description: '이것저것 하고싶은거 올리는 공간입니다。'
keyword: 'javascript, react, nodejs,'
url: 'https://gryrryfh.github.io' 
baseurl: ''
nav:
  home: '/'
  tags: '/tags.html'
footer:
  since: 2024
author: 'dlworud'
nickname: 'grry'
bio: '이것저것 합니다'
avatar: '/assets/img/poya.jpg'
search: true
nightMode: true
comments:
  disqus: false
  disqus_url: ''
mathjax: true
social-share: true
social-share-items: ['github', 'email', 'instagram', 'twitter']
theme-color: 'default'  # pink or default
postPatterns: 'circuitBoard'
sns:
  github: '//www.github.com/gryrryfh'
  email: '//jaegyeong135@gmail.com'
  instagram: '//www.instagram.com/jaegyeong567'
  twitter: '//www.x.com/Grrr138765'
recommend-tags: true
recommend-condition-size: 12
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
RSS: false
permalink: /:year/:month/:day/:title.html
plugins: [jekyll-paginate]
